// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPkjyx7jHEzmXGeXbwA2AFInIOEfd5_4s',
    appId: '1:556136750301:web:5ec5f71772addcaba44f34',
    messagingSenderId: '556136750301',
    projectId: 'flutter-auth-96765',
    authDomain: 'flutter-auth-96765.firebaseapp.com',
    storageBucket: 'flutter-auth-96765.appspot.com',
    measurementId: 'G-FMPQG7L4EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdKp5H--_-dMSZU6SKxUb6zMXJGqj3ic',
    appId: '1:556136750301:android:ab936b252e7d9246a44f34',
    messagingSenderId: '556136750301',
    projectId: 'flutter-auth-96765',
    storageBucket: 'flutter-auth-96765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcIvB4F5Q1eBS0t8CMflEKb4w1J1Z18EA',
    appId: '1:556136750301:ios:9600246ddb855909a44f34',
    messagingSenderId: '556136750301',
    projectId: 'flutter-auth-96765',
    storageBucket: 'flutter-auth-96765.appspot.com',
    iosBundleId: 'com.example.minimalEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcIvB4F5Q1eBS0t8CMflEKb4w1J1Z18EA',
    appId: '1:556136750301:ios:a8cad307cd6bd4c3a44f34',
    messagingSenderId: '556136750301',
    projectId: 'flutter-auth-96765',
    storageBucket: 'flutter-auth-96765.appspot.com',
    iosBundleId: 'com.example.minimalEcom.RunnerTests',
  );
}
